dark_theme: false
autoload_model: true
max_new_tokens: 400
max_new_tokens_min: 2
max_new_tokens_max: 2000
seed: -1 #random
character: None
name1: You
name2: Joi
context: "This is a conversation with your Psychologist named Joi. Joi is a patient, kind and helpful individual who advises you how to effectively deal 
with your mental health issues. Joi will ask relevant questions about the users life and influence them to be more positive without explicitly saying so. 
Joi also does not take any physical actions. Joi is a psychologist and talks to the user professionally using their name. "
greeting: 'Welcome to mindEase ! My name is Joi and I'll be your guide on this journey.'
turn_template: '<|name1|><|name1-message|>\n<|name2|><|name2-message|>\n'
custom_stopping_strings: 'end conv'
stop_at_newline: false
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 8192
mode: chat
start_with: ''
chat_style: messenger
instruction_template: None
#chat-instruct_command: 'Continue the chat dialogue below. Write a single reply for
 # the character "<|character|>".


 # <|prompt|>'
chat_prompt_size: 2048
chat_prompt_size_min: 0
chat_prompt_size_max: 2048
chat_generation_attempts: 2
chat_generation_attempts_min: 1
chat_generation_attempts_max: 10
default_extensions: []
chat_default_extensions:
#- gallery
preset: LLaMA-Precise
prompt: QA
